
name: Run Unix Port
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            
    - name: TESTRUN ruN
      run: |
        ls ./tools
        MICROPYPATH=./board tools/micropython -c "import sys;print(sys.path);import logging" 

    - name: run in linux 
      run: |
        MICROPYPATH=./board tools/micropython -c "import sys;print(sys.path);import logging" -m ./board/createstubs

    - name: run minified
      run: |
        MICROPYPATH=./board tools/micropython -c "import sys;print(sys.path);import logging" -m ./minified/createstubs
